name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set current date as env variable # pacola if coyping from https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows was a challenge:
      run: echo "NOW=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      
    - name: get PaK3 and the rest # now this is a fusion as the ntopp git and muder mystery git -pac
      run: | 
        sudo apt-get install -y nodejs
        sudo npm install argparse
        sudo npm install deasync
        sudo npm install jimp
        sudo npm install jszip
        git clone https://github.com/UnmatchedBracket/PaK3.git
        cd PaK3
        npm i

    - name: do the thing pls
      run: node PaK3/main.js src/ CL_SRB5b-$NOW.pk3

    - name: send thing to the action tab
      uses: actions/upload-artifact@v4
      with:
        name: srb5b
        path: CL_SRB5b-$NOW.pk3

    - name: could you preetty please send the file to the discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: CL_SRB5b-$NOW.pk3
